import type {
  ShowcaseScenario,
  ShowcaseScenarioId,
  ShowcaseSurface,
} from "./types";

export const SHOWCASE_SURFACES: Array<{
  id: ShowcaseSurface;
  label: string;
  description: string;
}> = [
  {
    id: "practice",
    label: "Practice",
    description: "Setup, audio, mic, prep, speaking, transitions, and AI rebuttal.",
  },
  {
    id: "feedback",
    label: "Feedback",
    description: "Results, verdicts, transcript review, annotations, and clash maps.",
  },
  {
    id: "duel",
    label: "Duels",
    description: "Create, matchmaking, lobby, live room, judging, and result states.",
  },
  {
    id: "popups",
    label: "Popups",
    description: "Code-owned feature, practice, reminder, survey, and thank-you popup states.",
  },
];

export const DEFAULT_SHOWCASE_SCENARIO_ID: ShowcaseScenarioId = "prep";

export const SHOWCASE_SCENARIOS: ShowcaseScenario[] = [
  {
    id: "practice-setup",
    surface: "practice",
    title: "Practice Setup",
    summary: "The selected motion, mode, side, timer, AI difficulty, and credit controls.",
    status: "ready",
    sourceComponent: "SessionConfig",
    viewport: "responsive",
    risk: "orb-navigation",
    riskNotes: "Showcase mode disables orb deduction and navigation.",
    showcaseSafe: true,
  },
  {
    id: "audio-check-idle",
    surface: "practice",
    title: "Audio Check - Idle",
    summary: "The pre-session TTS/audio unlock state before the test sound is played.",
    status: "ready",
    sourceComponent: "AudioCheck",
    viewport: "responsive",
    risk: "audio",
    riskNotes: "Controlled status renders without autoplay.",
    showcaseSafe: true,
  },
  {
    id: "audio-check-playing",
    surface: "practice",
    title: "Audio Check - Playing",
    summary: "Animated listening confirmation state for the audio check.",
    status: "ready",
    sourceComponent: "AudioCheck",
    viewport: "responsive",
    risk: "audio",
    riskNotes: "Controlled status renders the visual state without creating audio.",
    showcaseSafe: true,
  },
  {
    id: "audio-check-passed",
    surface: "practice",
    title: "Audio Check - Passed",
    summary: "The success state before moving to microphone setup.",
    status: "ready",
    sourceComponent: "AudioCheck",
    viewport: "responsive",
    risk: "audio",
    riskNotes: "Buttons are visible, but no audio plays unless explicitly clicked.",
    showcaseSafe: true,
  },
  {
    id: "mic-requesting",
    surface: "practice",
    title: "Mic Check - Requesting",
    summary: "The permission-request animation shown before browser permission resolves.",
    status: "ready",
    sourceComponent: "MicCheck",
    viewport: "responsive",
    risk: "microphone",
    riskNotes: "Controlled status bypasses getUserMedia.",
    showcaseSafe: true,
  },
  {
    id: "mic-testing",
    surface: "practice",
    title: "Mic Check - Testing",
    summary: "The microphone level meter while the learner speaks.",
    status: "ready",
    sourceComponent: "MicCheck",
    viewport: "responsive",
    risk: "microphone",
    riskNotes: "Fixture levels render without capturing audio.",
    showcaseSafe: true,
  },
  {
    id: "mic-denied",
    surface: "practice",
    title: "Mic Check - Permission Denied",
    summary: "Recovery guidance when the browser blocks microphone access.",
    status: "ready",
    sourceComponent: "MicCheck",
    viewport: "mobile",
    risk: "microphone",
    riskNotes: "Controlled status bypasses permission prompts.",
    showcaseSafe: true,
  },
  {
    id: "mic-not-found",
    surface: "practice",
    title: "Mic Check - Not Found",
    summary: "Fallback guidance when no microphone is detected.",
    status: "ready",
    sourceComponent: "MicCheck",
    viewport: "mobile",
    risk: "microphone",
    riskNotes: "Controlled status bypasses device probing.",
    showcaseSafe: true,
  },
  {
    id: "prep",
    surface: "practice",
    title: "Prep",
    summary: "Motion brief, compact timer, quick notes, and AI prep starter actions.",
    status: "ready",
    sourceComponent: "PrepPhase",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Pure fixture props.",
    showcaseSafe: true,
  },
  {
    id: "speaking-recording",
    surface: "practice",
    title: "Speaking - Recording",
    summary: "Live timer, recording state, notes, transcript, and action rail.",
    status: "ready",
    sourceComponent: "SpeakingPhase",
    viewport: "desktop",
    risk: "none",
    riskNotes: "Audio stream is null and transcription is fixture text.",
    showcaseSafe: true,
  },
  {
    id: "speaking-paused",
    surface: "practice",
    title: "Speaking - Paused",
    summary: "Paused recording state with resume affordance.",
    status: "ready",
    sourceComponent: "SpeakingPhase",
    viewport: "desktop",
    risk: "none",
    riskNotes: "Pure fixture props.",
    showcaseSafe: true,
  },
  {
    id: "speaking-network-error",
    surface: "practice",
    title: "Speaking - Network Error",
    summary: "The speech recognition recovery banner inside the speaking panel.",
    status: "ready",
    sourceComponent: "SpeakingPhase",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Speech error is fixture-only.",
    showcaseSafe: true,
  },
  {
    id: "speaking-end-confirm",
    surface: "practice",
    title: "Speaking - End Confirm",
    summary: "The early-end confirmation dialog layered over the speaking state.",
    status: "ready",
    sourceComponent: "SpeakingPhase",
    viewport: "mobile",
    risk: "none",
    riskNotes: "Dialog is opened by showcase prop.",
    showcaseSafe: true,
  },
  {
    id: "ai-rebuttal-loading",
    surface: "practice",
    title: "AI Rebuttal - Loading",
    summary: "AI preparing state before stream text appears.",
    status: "ready",
    sourceComponent: "AiRebuttalPhase",
    viewport: "desktop",
    risk: "ai-network",
    riskNotes: "Showcase status prevents API fetch.",
    showcaseSafe: true,
  },
  {
    id: "ai-rebuttal-streaming",
    surface: "practice",
    title: "AI Rebuttal - Streaming",
    summary: "Streaming response preview before final highlights arrive.",
    status: "ready",
    sourceComponent: "AiRebuttalPhase",
    viewport: "desktop",
    risk: "ai-network",
    riskNotes: "Streaming text is fixture-only.",
    showcaseSafe: true,
  },
  {
    id: "ai-rebuttal-done",
    surface: "practice",
    title: "AI Rebuttal - Done",
    summary: "Final AI rebuttal with highlighted claim, evidence, and impact spans.",
    status: "ready",
    sourceComponent: "AiRebuttalPhase",
    viewport: "desktop",
    risk: "ai-network",
    riskNotes: "Initial response prevents API fetch.",
    showcaseSafe: true,
  },
  {
    id: "ai-rebuttal-error",
    surface: "practice",
    title: "AI Rebuttal - Error",
    summary: "Failure state and retry action for AI response generation.",
    status: "ready",
    sourceComponent: "AiRebuttalPhase",
    viewport: "desktop",
    risk: "ai-network",
    riskNotes: "Error is injected by showcase props.",
    showcaseSafe: true,
  },
  {
    id: "transition-session-start",
    surface: "practice",
    title: "Transition - Session Start",
    summary: "Full-screen transition between mic check and prep.",
    status: "ready",
    sourceComponent: "TransitionOverlay",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Pure fixture props.",
    showcaseSafe: true,
  },
  {
    id: "transition-analyzing",
    surface: "practice",
    title: "Transition - Analyzing",
    summary: "Full-screen transition before the feedback route opens.",
    status: "ready",
    sourceComponent: "TransitionOverlay",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Pure fixture props.",
    showcaseSafe: true,
  },
  {
    id: "feedback-result",
    surface: "feedback",
    title: "Feedback Result",
    summary: "Default debate feedback dashboard with annotated transcript controls hidden.",
    status: "ready",
    sourceComponent: "SessionResultDashboard",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Pure fixture session.",
    showcaseSafe: true,
  },
  {
    id: "feedback-legacy",
    surface: "feedback",
    title: "Legacy Feedback",
    summary: "Compatibility state when older sessions do not include transcript annotations.",
    status: "ready",
    sourceComponent: "SessionResultDashboard",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Pure fixture session.",
    showcaseSafe: true,
  },
  {
    id: "feedback-history-overall",
    surface: "feedback",
    title: "History Review - Overall",
    summary: "History detail shell with the overall tab active.",
    status: "ready",
    sourceComponent: "SessionReviewShell",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Pure fixture session.",
    showcaseSafe: true,
    defaultTab: "overall",
  },
  {
    id: "feedback-history-transcript",
    surface: "feedback",
    title: "History Review - Transcript",
    summary: "Annotated transcript review with round filtering.",
    status: "ready",
    sourceComponent: "SessionTranscriptPanel",
    viewport: "mobile",
    risk: "none",
    riskNotes: "Pure fixture session.",
    showcaseSafe: true,
    defaultTab: "transcript",
  },
  {
    id: "feedback-history-clash",
    surface: "feedback",
    title: "History Review - Clash Map",
    summary: "Full-round clash map with answered, weighed, and dropped exchanges.",
    status: "ready",
    sourceComponent: "DebateClashMapPanel",
    viewport: "desktop",
    risk: "none",
    riskNotes: "Pure fixture session.",
    showcaseSafe: true,
    defaultTab: "clash",
  },
  {
    id: "feedback-ai-verdict",
    surface: "feedback",
    title: "AI Debate Verdict",
    summary: "Full-round verdict panel comparing user and AI performance.",
    status: "ready",
    sourceComponent: "DebateVerdictPanel",
    viewport: "desktop",
    risk: "none",
    riskNotes: "Pure fixture session.",
    showcaseSafe: true,
    defaultTab: "verdict",
  },
  {
    id: "feedback-unmatched-annotation",
    surface: "feedback",
    title: "Unmatched Annotation",
    summary: "Transcript fallback card when an annotation quote cannot be matched.",
    status: "ready",
    sourceComponent: "SessionTranscriptPanel",
    viewport: "mobile",
    risk: "none",
    riskNotes: "Fixture intentionally includes one missing quote.",
    showcaseSafe: true,
    defaultTab: "transcript",
  },
  {
    id: "popup-feature-announcement",
    surface: "popups",
    title: "Feature Announcement",
    summary: "Focused one-step announcement with illustration, short body, and two action choices.",
    status: "ready",
    sourceComponent: "FeatureNudgePopup",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Fixture popup only; CTA and dismiss actions are inert.",
    showcaseSafe: true,
  },
  {
    id: "popup-practice-suggestion",
    surface: "popups",
    title: "Practice Suggestion",
    summary: "Personalized debate practice nudge with two compact fact chips.",
    status: "ready",
    sourceComponent: "FeatureNudgePopup",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Fixture popup only; no analytics or navigation events fire.",
    showcaseSafe: true,
  },
  {
    id: "popup-reminder-opt-in",
    surface: "popups",
    title: "Reminder Opt-In",
    summary: "Email practice and streak reminder opt-in copy with scoped CTA wording.",
    status: "ready",
    sourceComponent: "FeatureNudgePopup",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Fixture popup only; the opt-in endpoint is not called.",
    showcaseSafe: true,
  },
  {
    id: "popup-feedback-survey",
    surface: "popups",
    title: "Feedback Survey",
    summary: "Two-button survey popup with reward chip and required-answer validation.",
    status: "ready",
    sourceComponent: "SurveyPopup",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Fixture answers stay local to the preview.",
    showcaseSafe: true,
  },
  {
    id: "popup-thank-you",
    surface: "popups",
    title: "Survey Thank-You",
    summary: "Post-submit reward confirmation after the survey flow completes.",
    status: "ready",
    sourceComponent: "SurveyThankYou",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Fixture completion state only.",
    showcaseSafe: true,
  },
  {
    id: "duel-create",
    surface: "duel",
    title: "Duel Create",
    summary: "Custom duel creation setup and preview.",
    status: "ready",
    sourceComponent: "DuelCreatePage",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Initial topics are fixture-only.",
    showcaseSafe: true,
  },
  {
    id: "duel-matchmaking",
    surface: "duel",
    title: "Duel Matchmaking",
    summary: "Matchmaking setup with category, difficulty, and queue preview.",
    status: "ready",
    sourceComponent: "DuelMatchmakingPage",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Initial topics are fixture-only.",
    showcaseSafe: true,
  },
  {
    id: "duel-lobby",
    surface: "duel",
    title: "Duel Lobby",
    summary: "Two-player room before both participants ready up.",
    status: "ready",
    sourceComponent: "DuelRoomFixturePreview",
    viewport: "responsive",
    risk: "duel-network",
    riskNotes: "Static fixture preview; no room actions call APIs.",
    showcaseSafe: true,
  },
  {
    id: "duel-live-prep",
    surface: "duel",
    title: "Duel Live - Prep",
    summary: "Shared prep phase with round flow and local notes.",
    status: "ready",
    sourceComponent: "DuelRoomFixturePreview",
    viewport: "desktop",
    risk: "duel-network",
    riskNotes: "Static fixture preview; no room actions call APIs.",
    showcaseSafe: true,
  },
  {
    id: "duel-live-speaking",
    surface: "duel",
    title: "Duel Live - Speaking",
    summary: "Active proposition speech phase with transcript/notes layout.",
    status: "ready",
    sourceComponent: "DuelRoomFixturePreview",
    viewport: "desktop",
    risk: "duel-network",
    riskNotes: "Static fixture preview; no room actions call APIs.",
    showcaseSafe: true,
  },
  {
    id: "duel-judging",
    surface: "duel",
    title: "Duel Judging",
    summary: "Post-speech AI judging state before verdict is available.",
    status: "ready",
    sourceComponent: "DuelRoomFixturePreview",
    viewport: "responsive",
    risk: "duel-network",
    riskNotes: "Static fixture preview; no room actions call APIs.",
    showcaseSafe: true,
  },
  {
    id: "duel-unavailable",
    surface: "duel",
    title: "Duel Unavailable",
    summary: "Error/empty state when a duel room cannot be loaded.",
    status: "ready",
    sourceComponent: "DuelUnavailablePreview",
    viewport: "mobile",
    risk: "none",
    riskNotes: "Static error copy.",
    showcaseSafe: true,
  },
  {
    id: "duel-result-overall",
    surface: "duel",
    title: "Duel Result - Overall",
    summary: "Judged duel result with participant feedback and ballot.",
    status: "ready",
    sourceComponent: "DuelResultContent",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Pure fixture room.",
    showcaseSafe: true,
    defaultTab: "overall",
  },
  {
    id: "duel-result-transcript",
    surface: "duel",
    title: "Duel Result - Transcript",
    summary: "Duel transcript tab with all speeches.",
    status: "ready",
    sourceComponent: "DuelResultContent",
    viewport: "mobile",
    risk: "none",
    riskNotes: "Pure fixture room.",
    showcaseSafe: true,
    defaultTab: "transcript",
  },
  {
    id: "duel-result-clash",
    surface: "duel",
    title: "Duel Result - Clash Map",
    summary: "Duel clash map with answered, misanswered, dropped, weighed, and turned links.",
    status: "ready",
    sourceComponent: "DuelResultContent",
    viewport: "desktop",
    risk: "none",
    riskNotes: "Pure fixture room.",
    showcaseSafe: true,
    defaultTab: "clash",
  },
  {
    id: "duel-result-legacy",
    surface: "duel",
    title: "Duel Result - Legacy",
    summary: "Result compatibility state when no duel clash links are present.",
    status: "ready",
    sourceComponent: "DuelResultContent",
    viewport: "responsive",
    risk: "none",
    riskNotes: "Pure fixture room.",
    showcaseSafe: true,
    defaultTab: "overall",
  },
];

export function getShowcaseScenario(id: string | null | undefined) {
  return (
    SHOWCASE_SCENARIOS.find((scenario) => scenario.id === id) ??
    SHOWCASE_SCENARIOS.find(
      (scenario) => scenario.id === DEFAULT_SHOWCASE_SCENARIO_ID
    )!
  );
}

export function getDefaultScenarioForSurface(surface: ShowcaseSurface) {
  if (surface === "practice") {
    return getShowcaseScenario(DEFAULT_SHOWCASE_SCENARIO_ID);
  }

  return (
    SHOWCASE_SCENARIOS.find((scenario) => scenario.surface === surface) ??
    getShowcaseScenario(DEFAULT_SHOWCASE_SCENARIO_ID)
  );
}

export function getScenariosForSurface(surface: ShowcaseSurface) {
  return SHOWCASE_SCENARIOS.filter((scenario) => scenario.surface === surface);
}

export function isShowcaseSurface(value: string | null | undefined): value is ShowcaseSurface {
  return SHOWCASE_SURFACES.some((surface) => surface.id === value);
}
