"use client";

import type { ComponentPropsWithoutRef } from "react";
import {
  ArchiveIcon,
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowsDownUpIcon,
  ArrowsInSimpleIcon,
  ArrowsLeftRightIcon,
  ArrowsOutSimpleIcon,
  BarbellIcon,
  BellRingingIcon,
  BookOpenIcon,
  BookOpenTextIcon,
  BookmarkIcon,
  BookmarkSimpleIcon,
  BrainIcon,
  BroadcastIcon,
  BuildingsIcon,
  CalendarBlankIcon,
  CalendarDotsIcon,
  CameraIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  ChartBarIcon,
  ChatCircleDotsIcon,
  ChatCircleIcon,
  ChatTextIcon,
  CheckCircleIcon,
  CheckIcon,
  CircleDashedIcon,
  ClipboardTextIcon,
  ClockCountdownIcon,
  ClockCounterClockwiseIcon,
  ClockIcon,
  CoinsIcon,
  CompassIcon,
  CopyIcon,
  CrownIcon,
  CursorClickIcon,
  DeviceMobileIcon,
  DotsSixVerticalIcon,
  DotsThreeIcon,
  DotsThreeVerticalIcon,
  DownloadSimpleIcon,
  EnvelopeIcon,
  EyeIcon,
  EyeSlashIcon,
  FileMagnifyingGlassIcon,
  FileTextIcon,
  FireIcon,
  FloppyDiskIcon,
  FunnelIcon,
  GaugeIcon,
  GearIcon,
  GiftIcon,
  GitBranchIcon,
  GlobeHemisphereWestIcon,
  GlobeIcon,
  GraduationCapIcon,
  GridFourIcon,
  HeadCircuitIcon,
  HouseIcon,
  ImageSquareIcon,
  InfoIcon,
  LaptopIcon,
  LayoutIcon,
  LightbulbIcon,
  LightningIcon,
  LinkIcon,
  LinkSimpleIcon,
  ListBulletsIcon,
  ListChecksIcon,
  ListIcon,
  ListNumbersIcon,
  LockIcon,
  LockOpenIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MedalIcon,
  MegaphoneIcon,
  MicrophoneIcon,
  MicrophoneSlashIcon,
  MicrophoneStageIcon,
  MinusIcon,
  PaperclipIcon,
  PaperPlaneRightIcon,
  PauseIcon,
  PenIcon,
  PenNibIcon,
  PencilSimpleIcon,
  PlantIcon,
  PlayCircleIcon,
  PlayIcon,
  PlusIcon,
  PulseIcon,
  QuestionIcon,
  QuotesIcon,
  RepeatIcon,
  RobotIcon,
  ScalesIcon,
  SealCheckIcon,
  ShareNetworkIcon,
  ShieldCheckIcon,
  ShieldIcon,
  ShuffleIcon,
  SidebarSimpleIcon,
  SignOutIcon,
  SlidersHorizontalIcon,
  SmileyIcon,
  SparkleIcon,
  SpeakerHighIcon,
  SpinnerIcon,
  SquareIcon,
  StackIcon,
  StackSimpleIcon,
  StarIcon,
  SwordIcon,
  TargetIcon,
  TextBIcon,
  TextItalicIcon,
  TextUnderlineIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TimerIcon,
  TranslateIcon,
  TrashIcon,
  TrendDownIcon,
  TrendUpIcon,
  TrophyIcon,
  UploadSimpleIcon,
  UserCircleIcon,
  UserCirclePlusIcon,
  UserIcon,
  UserPlusIcon,
  UsersIcon,
  UsersThreeIcon,
  WarningCircleIcon,
  WarningIcon,
  WaveformIcon,
  WifiHighIcon,
  WifiSlashIcon,
  XCircleIcon,
  XIcon,
  type Icon as PhosphorIcon,
  type IconProps as PhosphorIconProps,
  type IconWeight,
} from "@phosphor-icons/react";

import { cn } from "@/lib/utils";

export type ProductIconComponent = PhosphorIcon;
export type ProductIconProps = PhosphorIconProps;
export type ProductIconWeight = IconWeight;

export const iconSizes = {
  xs: 14,
  sm: 16,
  md: 20,
  lg: 24,
  xl: 32,
} as const;

export const iconTones = {
  current: "",
  muted: "text-on-surface-variant",
  neutral: "text-on-surface",
  primary: "text-primary",
  success: "text-success",
  warning: "text-warning",
  danger: "text-error",
  inverse: "text-on-primary",
} as const;

export const iconRegistry = {
  activity: PulseIcon,
  alert: WarningCircleIcon,
  archive: ArchiveIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  arrowRightLeft: ArrowsLeftRightIcon,
  arrowUpDown: ArrowsDownUpIcon,
  award: MedalIcon,
  badgeCheck: SealCheckIcon,
  bold: TextBIcon,
  book: BookOpenIcon,
  bookCheck: BookOpenTextIcon,
  bookText: BookOpenTextIcon,
  bookmark: BookmarkIcon,
  bookmarkQuiet: BookmarkSimpleIcon,
  bot: RobotIcon,
  brain: BrainIcon,
  brainCircuit: HeadCircuitIcon,
  building: BuildingsIcon,
  calendar: CalendarBlankIcon,
  calendarClock: CalendarDotsIcon,
  camera: CameraIcon,
  chart: ChartBarIcon,
  check: CheckIcon,
  checkCircle: CheckCircleIcon,
  chevronDown: CaretDownIcon,
  chevronLeft: CaretLeftIcon,
  chevronRight: CaretRightIcon,
  chevronUp: CaretUpIcon,
  circleDashed: CircleDashedIcon,
  clipboard: ClipboardTextIcon,
  clock: ClockIcon,
  coins: CoinsIcon,
  compass: CompassIcon,
  copy: CopyIcon,
  crown: CrownIcon,
  dashboard: HouseIcon,
  debate: ScalesIcon,
  download: DownloadSimpleIcon,
  drag: DotsSixVerticalIcon,
  duel: SwordIcon,
  edit: PencilSimpleIcon,
  expand: ArrowsOutSimpleIcon,
  external: ArrowSquareOutIcon,
  eye: EyeIcon,
  eyeOff: EyeSlashIcon,
  fileSearch: FileMagnifyingGlassIcon,
  fileText: FileTextIcon,
  filter: FunnelIcon,
  fire: FireIcon,
  gauge: GaugeIcon,
  gift: GiftIcon,
  globe: GlobeIcon,
  globeAlt: GlobeHemisphereWestIcon,
  graduation: GraduationCapIcon,
  grid: GridFourIcon,
  help: QuestionIcon,
  history: ClockCounterClockwiseIcon,
  image: ImageSquareIcon,
  import: UploadSimpleIcon,
  info: InfoIcon,
  italic: TextItalicIcon,
  language: TranslateIcon,
  laptop: LaptopIcon,
  layers: StackIcon,
  layersAlt: StackSimpleIcon,
  layout: LayoutIcon,
  lightbulb: LightbulbIcon,
  link: LinkIcon,
  linkSimple: LinkSimpleIcon,
  list: ListIcon,
  listBullets: ListBulletsIcon,
  listChecks: ListChecksIcon,
  listNumbers: ListNumbersIcon,
  loader: SpinnerIcon,
  lock: LockIcon,
  logOut: SignOutIcon,
  mail: EnvelopeIcon,
  mapPin: MapPinIcon,
  medal: MedalIcon,
  megaphone: MegaphoneIcon,
  menu: ListIcon,
  message: ChatTextIcon,
  messageCircle: ChatCircleIcon,
  messageDots: ChatCircleDotsIcon,
  mic: MicrophoneIcon,
  micOff: MicrophoneSlashIcon,
  micStage: MicrophoneStageIcon,
  minimize: ArrowsInSimpleIcon,
  minus: MinusIcon,
  moreHorizontal: DotsThreeIcon,
  moreVertical: DotsThreeVerticalIcon,
  mouseClick: CursorClickIcon,
  panelLeftClose: SidebarSimpleIcon,
  paperclip: PaperclipIcon,
  pause: PauseIcon,
  pen: PenIcon,
  penLine: PenNibIcon,
  play: PlayIcon,
  playCircle: PlayCircleIcon,
  plus: PlusIcon,
  quote: QuotesIcon,
  radar: BroadcastIcon,
  refresh: ArrowClockwiseIcon,
  repeat: RepeatIcon,
  rotateBack: ArrowCounterClockwiseIcon,
  save: FloppyDiskIcon,
  scale: ScalesIcon,
  search: MagnifyingGlassIcon,
  send: PaperPlaneRightIcon,
  settings: GearIcon,
  share: ShareNetworkIcon,
  shield: ShieldIcon,
  shieldCheck: ShieldCheckIcon,
  shuffle: ShuffleIcon,
  sliders: SlidersHorizontalIcon,
  smartphone: DeviceMobileIcon,
  smile: SmileyIcon,
  sparkles: SparkleIcon,
  sprout: PlantIcon,
  square: SquareIcon,
  star: StarIcon,
  target: TargetIcon,
  thumbsDown: ThumbsDownIcon,
  thumbsUp: ThumbsUpIcon,
  timer: TimerIcon,
  timerReset: ClockCountdownIcon,
  trash: TrashIcon,
  trendingDown: TrendDownIcon,
  trendingUp: TrendUpIcon,
  trophy: TrophyIcon,
  underline: TextUnderlineIcon,
  unlock: LockOpenIcon,
  user: UserIcon,
  userCircle: UserCircleIcon,
  userCirclePlus: UserCirclePlusIcon,
  userPlus: UserPlusIcon,
  users: UsersIcon,
  usersGroup: UsersThreeIcon,
  volume: SpeakerHighIcon,
  wand: MagicWandIcon,
  warning: WarningIcon,
  waves: WaveformIcon,
  wifi: WifiHighIcon,
  wifiOff: WifiSlashIcon,
  x: XIcon,
  xCircle: XCircleIcon,
  zap: LightningIcon,
} as const;

export type ProductIconName = keyof typeof iconRegistry;
export type ProductIconSize = keyof typeof iconSizes;
export type ProductIconTone = keyof typeof iconTones;

interface SemanticProductIconProps
  extends Omit<ComponentPropsWithoutRef<"svg">, "color" | "children"> {
  name: ProductIconName;
  size?: ProductIconSize | number;
  tone?: ProductIconTone;
  weight?: IconWeight;
  decorative?: boolean;
  label?: string;
}

export function ProductIcon({
  name,
  size = "md",
  tone = "current",
  weight = "regular",
  decorative = true,
  label,
  className,
  ...props
}: SemanticProductIconProps) {
  const Icon = iconRegistry[name];
  const resolvedSize = typeof size === "number" ? size : iconSizes[size];

  return (
    <Icon
      aria-hidden={decorative ? "true" : undefined}
      aria-label={!decorative ? label : undefined}
      className={cn("shrink-0", iconTones[tone], className)}
      size={resolvedSize}
      weight={weight}
      {...props}
    />
  );
}

export const legacyIcons = {
  Activity: iconRegistry.activity,
  AlertCircle: iconRegistry.alert,
  AlertTriangle: iconRegistry.warning,
  Archive: iconRegistry.archive,
  ArrowLeft: iconRegistry.arrowLeft,
  ArrowRight: iconRegistry.arrowRight,
  ArrowRightLeft: iconRegistry.arrowRightLeft,
  ArrowUpDown: iconRegistry.arrowUpDown,
  Award: iconRegistry.award,
  BadgeCheck: iconRegistry.badgeCheck,
  BarChart3: iconRegistry.chart,
  BellRing: BellRingingIcon,
  Bold: iconRegistry.bold,
  BookOpen: iconRegistry.book,
  BookOpenCheck: iconRegistry.bookCheck,
  BookOpenText: iconRegistry.bookText,
  Bookmark: iconRegistry.bookmark,
  BookmarkCheck: iconRegistry.bookmarkQuiet,
  Bot: iconRegistry.bot,
  Brain: iconRegistry.brain,
  BrainCircuit: iconRegistry.brainCircuit,
  Building2: iconRegistry.building,
  CalendarClock: iconRegistry.calendarClock,
  CalendarDays: iconRegistry.calendar,
  Camera: iconRegistry.camera,
  ChartColumnBig: iconRegistry.chart,
  Check: iconRegistry.check,
  CheckCircle2: iconRegistry.checkCircle,
  CheckIcon: iconRegistry.check,
  ChevronDown: iconRegistry.chevronDown,
  ChevronDownIcon: iconRegistry.chevronDown,
  ChevronLeft: iconRegistry.chevronLeft,
  ChevronRight: iconRegistry.chevronRight,
  ChevronRightIcon: iconRegistry.chevronRight,
  ChevronUp: iconRegistry.chevronUp,
  ChevronUpIcon: iconRegistry.chevronUp,
  CircleAlert: iconRegistry.alert,
  CircleDashed: iconRegistry.circleDashed,
  CircleHelp: iconRegistry.help,
  ClipboardList: iconRegistry.clipboard,
  Clock: iconRegistry.clock,
  Clock3: iconRegistry.clock,
  Coins: iconRegistry.coins,
  Compass: iconRegistry.compass,
  Copy: iconRegistry.copy,
  Crown: iconRegistry.crown,
  Download: iconRegistry.download,
  Dumbbell: BarbellIcon,
  Edit3: iconRegistry.edit,
  Expand: iconRegistry.expand,
  ExternalLink: iconRegistry.external,
  Eye: iconRegistry.eye,
  EyeOff: iconRegistry.eyeOff,
  FileSearch: iconRegistry.fileSearch,
  FileText: iconRegistry.fileText,
  Filter: iconRegistry.filter,
  Flame: iconRegistry.fire,
  Gauge: iconRegistry.gauge,
  Gift: iconRegistry.gift,
  GitBranch: GitBranchIcon,
  Globe: iconRegistry.globe,
  Globe2: iconRegistry.globeAlt,
  GraduationCap: iconRegistry.graduation,
  GripVertical: iconRegistry.drag,
  HelpCircle: iconRegistry.help,
  History: iconRegistry.history,
  Home: iconRegistry.dashboard,
  ImagePlus: iconRegistry.image,
  Import: iconRegistry.import,
  Info: iconRegistry.info,
  Italic: iconRegistry.italic,
  Languages: iconRegistry.language,
  Laptop: iconRegistry.laptop,
  Layers: iconRegistry.layers,
  Layers3: iconRegistry.layersAlt,
  LayoutDashboard: iconRegistry.layout,
  LayoutGrid: iconRegistry.grid,
  LayoutList: iconRegistry.listBullets,
  Lightbulb: iconRegistry.lightbulb,
  Link: iconRegistry.link,
  Link2: iconRegistry.linkSimple,
  List: iconRegistry.list,
  ListChecks: iconRegistry.listChecks,
  ListFilter: iconRegistry.filter,
  ListOrdered: iconRegistry.listNumbers,
  Loader2: iconRegistry.loader,
  Lock: iconRegistry.lock,
  LogOut: iconRegistry.logOut,
  Mail: iconRegistry.mail,
  MapPin: iconRegistry.mapPin,
  Medal: iconRegistry.medal,
  Megaphone: iconRegistry.megaphone,
  Menu: iconRegistry.menu,
  MessageCircle: iconRegistry.messageCircle,
  MessageCircleMore: iconRegistry.messageDots,
  MessageSquare: iconRegistry.message,
  MessageSquareQuote: iconRegistry.quote,
  MessageSquareText: iconRegistry.message,
  Mic: iconRegistry.mic,
  Mic2: iconRegistry.micStage,
  MicOff: iconRegistry.micOff,
  Minimize2: iconRegistry.minimize,
  Minus: iconRegistry.minus,
  MoreHorizontal: iconRegistry.moreHorizontal,
  MoreVertical: iconRegistry.moreVertical,
  MousePointerClick: iconRegistry.mouseClick,
  PanelLeftClose: iconRegistry.panelLeftClose,
  Paperclip: iconRegistry.paperclip,
  Pause: iconRegistry.pause,
  PenLine: iconRegistry.penLine,
  PenTool: iconRegistry.pen,
  Play: iconRegistry.play,
  PlayCircle: iconRegistry.playCircle,
  Plus: iconRegistry.plus,
  Quote: iconRegistry.quote,
  Radar: iconRegistry.radar,
  RefreshCw: iconRegistry.refresh,
  Repeat2: iconRegistry.repeat,
  RotateCcw: iconRegistry.rotateBack,
  Save: iconRegistry.save,
  Scale: iconRegistry.scale,
  Search: iconRegistry.search,
  Send: iconRegistry.send,
  Settings: iconRegistry.settings,
  Share2: iconRegistry.share,
  Shield: iconRegistry.shield,
  ShieldCheck: iconRegistry.shieldCheck,
  Shuffle: iconRegistry.shuffle,
  SlidersHorizontal: iconRegistry.sliders,
  Smartphone: iconRegistry.smartphone,
  Smile: iconRegistry.smile,
  Sparkles: iconRegistry.sparkles,
  Sprout: iconRegistry.sprout,
  Square: iconRegistry.square,
  Star: iconRegistry.star,
  Swords: iconRegistry.duel,
  Target: iconRegistry.target,
  ThumbsDown: iconRegistry.thumbsDown,
  ThumbsUp: iconRegistry.thumbsUp,
  Timer: iconRegistry.timer,
  TimerReset: iconRegistry.timerReset,
  Trash2: iconRegistry.trash,
  TrendingDown: iconRegistry.trendingDown,
  TrendingUp: iconRegistry.trendingUp,
  Trophy: iconRegistry.trophy,
  Underline: iconRegistry.underline,
  Unlock: iconRegistry.unlock,
  User: iconRegistry.user,
  UserPlus: iconRegistry.userPlus,
  UserRound: iconRegistry.userCircle,
  UserRoundPlus: iconRegistry.userCirclePlus,
  Users: iconRegistry.users,
  Users2: iconRegistry.usersGroup,
  UsersRound: iconRegistry.usersGroup,
  Volume2: iconRegistry.volume,
  Wand2: iconRegistry.wand,
  Waves: iconRegistry.waves,
  Wifi: iconRegistry.wifi,
  WifiOff: iconRegistry.wifiOff,
  X: iconRegistry.x,
  XCircle: iconRegistry.xCircle,
  XIcon: iconRegistry.x,
  Zap: iconRegistry.zap,
} satisfies Record<string, ProductIconComponent>;
