import type {
  IeltsGoalModel,
  IeltsLearnAtom,
  IeltsWeaknessSignal,
} from "./types";

export const AS_OF = "2026-06-20T12:00:00.000Z";
export const FIXTURE_USER_ID = "00000000-0000-4000-8000-000000000101";

export const fixtureIeltsWeaknessSignals: IeltsWeaknessSignal[] = [
  {
    skill: "reading",
    key: "reading:matching_headings",
    labelEn: "Matching headings",
    labelVi: "Ghép tiêu đề đoạn văn",
    severity: "critical",
    confidence: 0.78,
    evidenceCount: 7,
    currentValue: 5.5,
    targetValue: 6.5,
    reasonEn: "Recent heading items are below the target band.",
    reasonVi: "Các câu ghép tiêu đề gần đây đang thấp hơn mục tiêu.",
    recommendedActivityFilters: {
      skill: "reading",
      questionTypes: ["matching_headings"],
      subskillTags: ["reading:matching_headings"],
    },
  },
  {
    skill: "listening",
    key: "listening:map_plan_label",
    labelEn: "Map and plan labels",
    labelVi: "Ghi nhãn bản đồ và sơ đồ",
    severity: "weak",
    confidence: 0.66,
    evidenceCount: 5,
    currentValue: 6,
    targetValue: 6.5,
    reasonEn: "Distractors in map-label questions are causing misses.",
    reasonVi: "Các bẫy trong câu ghi nhãn bản đồ đang gây lỗi.",
    recommendedActivityFilters: {
      skill: "listening",
      questionTypes: ["map_plan_label"],
      subskillTags: ["listening:spatial_signposting"],
    },
  },
  {
    skill: "writing",
    key: "writing:coherence_cohesion",
    labelEn: "Coherence and cohesion",
    labelVi: "Mạch lạc và liên kết",
    severity: "critical",
    confidence: 0.72,
    evidenceCount: 3,
    currentValue: 5.5,
    targetValue: 6.5,
    reasonEn: "Task 2 paragraphs need clearer progression and linking.",
    reasonVi: "Đoạn thân bài Task 2 cần phát triển ý và liên kết rõ hơn.",
    recommendedActivityFilters: {
      skill: "writing",
      criteria: ["coherence_cohesion"],
      subskillTags: ["writing:coherence_cohesion"],
    },
  },
  {
    skill: "speaking",
    key: "speaking:phoneme_th",
    labelEn: "Pronunciation: /th/ contrast",
    labelVi: "Phát âm: phân biệt âm /th/",
    severity: "watch",
    confidence: 0.58,
    evidenceCount: 4,
    currentValue: 6,
    targetValue: 6.5,
    reasonEn: "Phoneme evidence shows recurring /th/ substitutions.",
    reasonVi: "Dữ liệu âm vị cho thấy lỗi thay thế /th/ lặp lại.",
    recommendedActivityFilters: {
      skill: "speaking",
      criteria: ["pronunciation"],
      subskillTags: ["speaking:pronunciation", "phoneme:th"],
    },
  },
];

export const fixtureIeltsStrengthSignals: IeltsWeaknessSignal[] = [
  {
    skill: "listening",
    key: "listening:signposting",
    labelEn: "Signposting",
    labelVi: "Tín hiệu chuyển ý",
    severity: "watch",
    confidence: 0.7,
    evidenceCount: 6,
    currentValue: 7,
    targetValue: 6.5,
    reasonEn: "Recent section evidence is above the target band.",
    reasonVi: "Dữ liệu phần nghe gần đây đang cao hơn mục tiêu.",
    recommendedActivityFilters: {
      skill: "listening",
      subskillTags: ["listening:signposting"],
    },
  },
];

export const fixtureIeltsLearnAtoms: IeltsLearnAtom[] = [
  {
    activityType: "ielts_vocab_collocation",
    skill: "writing",
    focusArea: "academic collocations for Task 2",
    estimatedMinutes: 8,
    questionIds: [],
    rendererTags: ["vocabulary", "collocation"],
    scoringMode: "objective",
  },
  {
    activityType: "ielts_paraphrase_transform",
    skill: "reading",
    focusArea: "synonym recognition",
    estimatedMinutes: 10,
    questionIds: ["00000000-0000-4000-8000-000000000201"],
    rendererTags: ["paraphrase"],
    scoringMode: "objective",
  },
  {
    activityType: "ielts_gap_fill",
    skill: "listening",
    focusArea: "note completion",
    estimatedMinutes: 12,
    questionIds: ["00000000-0000-4000-8000-000000000202"],
    rendererTags: ["completion"],
    scoringMode: "objective",
  },
  {
    activityType: "ielts_tfng_reasoning",
    skill: "reading",
    focusArea: "claim verification",
    estimatedMinutes: 4,
    questionIds: ["00000000-0000-4000-8000-000000000207"],
    rendererTags: ["tfng", "reasoning"],
    scoringMode: "objective",
  },
  {
    activityType: "ielts_scan_detail",
    skill: "reading",
    focusArea: "specific detail scanning",
    estimatedMinutes: 5,
    questionIds: ["00000000-0000-4000-8000-000000000208"],
    rendererTags: ["scan", "detail"],
    scoringMode: "objective",
  },
  {
    activityType: "ielts_sentence_transform",
    skill: "writing",
    focusArea: "sentence transformation",
    estimatedMinutes: 4,
    questionIds: ["00000000-0000-4000-8000-000000000209"],
    rendererTags: ["sentence_transform"],
    scoringMode: "objective",
  },
  {
    activityType: "ielts_cohesion_linker",
    skill: "writing",
    focusArea: "cohesive devices",
    estimatedMinutes: 5,
    questionIds: ["00000000-0000-4000-8000-000000000210"],
    rendererTags: ["cohesion", "linker"],
    scoringMode: "objective",
  },
  {
    activityType: "ielts_listening_micro_clip",
    skill: "listening",
    focusArea: "map-label distractors",
    estimatedMinutes: 7,
    questionIds: ["00000000-0000-4000-8000-000000000203"],
    rendererTags: ["listening", "micro_clip"],
    scoringMode: "objective",
  },
  {
    activityType: "ielts_pronunciation_minimal_pair",
    skill: "speaking",
    focusArea: "/th/ minimal pairs",
    estimatedMinutes: 6,
    questionIds: [],
    rendererTags: ["pronunciation", "phoneme"],
    scoringMode: "ai_speaking",
  },
  {
    activityType: "ielts_reading_skim_scan",
    skill: "reading",
    focusArea: "matching headings",
    estimatedMinutes: 12,
    questionIds: ["00000000-0000-4000-8000-000000000204"],
    rendererTags: ["reading", "skim_scan"],
    scoringMode: "objective",
  },
  {
    activityType: "ielts_grammar_fix",
    skill: "writing",
    focusArea: "complex sentence accuracy",
    estimatedMinutes: 8,
    questionIds: [],
    rendererTags: ["grammar"],
    scoringMode: "self_check",
  },
  {
    activityType: "ielts_strategy_chunk",
    skill: "reading",
    focusArea: "heading strategy",
    estimatedMinutes: 15,
    questionIds: ["00000000-0000-4000-8000-000000000205"],
    rendererTags: ["strategy", "lesson"],
    scoringMode: "self_check",
  },
  {
    activityType: "ielts_speaking_fluency_prompt",
    skill: "speaking",
    focusArea: "Part 2 timing",
    estimatedMinutes: 10,
    questionIds: ["00000000-0000-4000-8000-000000000206"],
    rendererTags: ["speaking", "fluency"],
    scoringMode: "ai_speaking",
  },
];

export const fixtureIeltsGoal: IeltsGoalModel = {
  module: "academic",
  targetOverallBand: 6.5,
  targetSkillBands: {
    writing: 7,
    speaking: 6.5,
  },
  targetTestDate: "2026-09-01",
  focusSkills: ["writing", "speaking"],
  availability: {
    studyDays: [1, 3, 5],
    dailyMinutes: 30,
    timezone: "Asia/Ho_Chi_Minh",
    preferredIntensity: "standard",
  },
  feedbackLanguage: "en",
};
