import type { DashboardHomeData } from "@thinkfy/shared/dashboard";

const today = new Date().toISOString();

export const previewDashboardData: DashboardHomeData = {
  profile: {
    id: "preview-user",
    email: "preview@thinkfy.local",
    display_name: "Thinkfy Student",
    avatar_url: null,
    role: "student",
    streak_current: 7,
    streak_longest: 14,
    streak_last_active_date: today.slice(0, 10),
    total_practice_minutes: 184,
    total_sessions_completed: 18,
    xp: 420,
    level: 4,
    onboarding_completed: true,
    preferences: { daily_goal_minutes: 30 },
    selected_title: null,
    unlocked_titles: [],
    banner_color: "#00B8D9",
    referral_code: null,
    orb_balance: 12,
    referred_by: null,
    created_at: today,
    updated_at: today,
  },
  nav: [],
  topBar: {
    currentStreak: 7,
    orbBalance: 12,
    level: 4,
    xpCurrent: 420,
    xpGoal: 500,
    pendingNotifications: 0,
  },
  hero: {
    weeklyStats: [],
    todayGoal: {
      goalMinutes: 30,
      practicedMinutes: 18,
      remainingMinutes: 12,
      progressPercent: 60,
      metGoal: false,
    },
    weeklyGoal: {
      goalMinutes: 100,
      practicedMinutes: 86,
      remainingMinutes: 14,
      progressPercent: 86,
      metGoal: false,
    },
  },
  skillSnapshot: {
    metrics: [],
    overallScore: 76,
    weakestSkill: "rebuttal",
    strongestSkill: "clarity",
    sourceSessions: 8,
    confidence: 0.72,
    trackBreakdown: { debate: 5, speaking: 3 },
    difficultyBreakdown: {
      topic: { beginner: 2, intermediate: 4, advanced: 2 },
      ai: { easy: 1, medium: 5, hard: 2, none: 0 },
    },
  },
  recommendedDrill: {
    key: "weakest-skill",
    href: "/practice?track=debate",
    detailHref: "/profile",
    ctaKey: "start",
    durationMinutes: 10,
    context: null,
    scoreOutOf100: 68,
    skillKey: "rebuttal",
    track: "debate",
  },
  quickActions: [
    {
      key: "speaking",
      href: "/practice?track=speaking",
      status: "live",
      descriptionKey: "action_speaking_desc",
    },
    {
      key: "debate",
      href: "/practice?track=debate",
      status: "live",
      descriptionKey: "action_debate_desc",
    },
    {
      key: "course",
      href: "/courses",
      status: "live",
      descriptionKey: "action_course_desc",
    },
    {
      key: "coach",
      href: "/chat?context=coach-home",
      status: "live",
      descriptionKey: "action_coach_desc",
    },
  ],
  recentActivity: [
    {
      id: "preview-session-1",
      kind: "debate",
      title: "School uniforms debate",
      subtitle: "Debate Practice",
      createdAt: today,
      href: "/history/preview-session-1",
      scoreOutOf100: 82,
      statusLabel: "Proficient",
      progressPercent: null,
    },
    {
      id: "preview-session-2",
      kind: "speaking",
      title: "Social media limits",
      subtitle: "Speaking Practice",
      createdAt: today,
      href: "/history/preview-session-2",
      scoreOutOf100: 74,
      statusLabel: "Competent",
      progressPercent: null,
    },
  ],
  todayPlanItems: [
    {
      id: "review-preview",
      key: "review-feedback",
      href: "/history/preview-session-1",
      ctaKey: "review",
      durationMinutes: 7,
      context: "School uniforms debate",
      scoreOutOf100: 82,
      track: "debate",
    },
    {
      id: "coach-check",
      key: "coach-check",
      href: "/chat?context=coach-home",
      ctaKey: "ask-coach",
      durationMinutes: 5,
      context: null,
    },
  ],
  progress: [
    {
      key: "total-sessions",
      value: 18,
      displayValue: "18",
      delta: 3,
    },
    {
      key: "strong-rate",
      value: 72,
      displayValue: "72%",
      delta: 8,
    },
    {
      key: "average-score",
      value: 76,
      displayValue: "76 /100",
      delta: 4,
    },
    {
      key: "practice-time",
      value: 42,
      displayValue: "42 min",
      delta: 12,
    },
  ],
  sidebarCards: {
    dailyGoal: {
      goalMinutes: 30,
      practicedMinutes: 18,
      remainingMinutes: 12,
      progressPercent: 60,
      metGoal: false,
    },
    inviteOrbs: 5,
    referralCode: null,
  },
  courseContinuation: {
    courseId: "preview-course",
    title: "Debate Foundations",
    category: "debate",
    progressPercent: 42,
    href: "/courses",
  },
};
