export const MATERIAL_COPY = {
  en: {
    materials: "Materials",
    library: "Material library",
    libraryDescription:
      "Prepare, review, and place materials into learning moments.",
    upload: "Upload material",
    search: "Search materials",
    allStatuses: "All statuses",
    noMaterials: "No materials have been shared yet.",
    noMatches: "No materials match these filters.",
    open: "Open",
    close: "Close material",
    retry: "Try again",
    download: "Open accessible copy",
    required: "Required",
    optional: "Optional",
    lesson: "Lesson",
    updated: "Updated",
    placement: "Placement",
    place: "Place in lesson",
    review: "Review draft",
    viewStudent: "View as student",
    rights: "Rights",
    rightsApproved: "Approved",
    rightsReview: "Approval required",
    previewUnavailable: "A safe preview is not available yet.",
    previewExpired:
      "This secure preview expired. Refresh the material to continue.",
    processing: "This material is still being prepared.",
    failed: "We could not prepare this material.",
    rejected: "This file was rejected during safety checks.",
    withdraw: "Withdraw material",
    withdrawn: "This material is no longer available.",
    scheduled: "Scheduled",
    published: "Published",
    draft: "Draft",
    page: "Page",
    previousPage: "Previous page",
    nextPage: "Next page",
    transcript: "Transcript",
    noTranscript: "A transcript is not available for this audio.",
    documentUnavailable:
      "This document cannot be displayed in the native viewer.",
    table: "Table",
    audio: "Audio",
    answer: "Your answer",
    readonlyAnswer: "Answers are not collected in material preview.",
    teacherWorkspace: "Teacher workspace",
    filters: "Material filters",
    clearFilters: "Clear filters",
    uploadUnavailable:
      "Upload actions will appear when the materials service is connected.",
    learnerView: "Learner preview",
    learnerViewDescription:
      "This uses the same published projection learners receive.",
    placementStatus: "Placement status",
    processingStatus: "File status",
    release: "Release",
    audience: "Audience",
  },
  vi: {
    materials: "Tài liệu",
    library: "Thư viện tài liệu",
    libraryDescription:
      "Chuẩn bị, duyệt và đặt tài liệu vào đúng thời điểm học.",
    upload: "Tải tài liệu lên",
    search: "Tìm tài liệu",
    allStatuses: "Tất cả trạng thái",
    noMaterials: "Chưa có tài liệu nào được chia sẻ.",
    noMatches: "Không có tài liệu phù hợp với bộ lọc.",
    open: "Mở",
    close: "Đóng tài liệu",
    retry: "Thử lại",
    download: "Mở bản có thể truy cập",
    required: "Bắt buộc",
    optional: "Không bắt buộc",
    lesson: "Bài học",
    updated: "Cập nhật",
    placement: "Vị trí học",
    place: "Đặt vào bài học",
    review: "Duyệt bản nháp",
    viewStudent: "Xem như học viên",
    rights: "Quyền sử dụng",
    rightsApproved: "Đã phê duyệt",
    rightsReview: "Cần phê duyệt",
    previewUnavailable: "Bản xem trước an toàn chưa sẵn sàng.",
    previewExpired:
      "Bản xem trước bảo mật đã hết hạn. Hãy tải lại để tiếp tục.",
    processing: "Tài liệu này vẫn đang được chuẩn bị.",
    failed: "Không thể chuẩn bị tài liệu này.",
    rejected: "Tệp đã bị từ chối trong quá trình kiểm tra an toàn.",
    withdraw: "Thu hồi tài liệu",
    withdrawn: "Tài liệu này không còn khả dụng.",
    scheduled: "Đã lên lịch",
    published: "Đã xuất bản",
    draft: "Bản nháp",
    page: "Trang",
    previousPage: "Trang trước",
    nextPage: "Trang sau",
    transcript: "Bản ghi lời",
    noTranscript: "Tệp âm thanh này chưa có bản ghi lời.",
    documentUnavailable: "Không thể hiển thị tài liệu này trong trình đọc.",
    table: "Bảng",
    audio: "Âm thanh",
    answer: "Câu trả lời của bạn",
    readonlyAnswer: "Bản xem trước tài liệu không thu câu trả lời.",
    teacherWorkspace: "Không gian giáo viên",
    filters: "Bộ lọc tài liệu",
    clearFilters: "Xóa bộ lọc",
    uploadUnavailable:
      "Tính năng tải lên sẽ xuất hiện khi dịch vụ tài liệu được kết nối.",
    learnerView: "Bản xem của học viên",
    learnerViewDescription:
      "Nội dung này dùng đúng bản đã xuất bản mà học viên nhận được.",
    placementStatus: "Trạng thái phát hành",
    processingStatus: "Trạng thái tệp",
    release: "Phát hành",
    audience: "Người nhận",
  },
} as const;

export function materialCopy(locale: string) {
  return locale === "vi" ? MATERIAL_COPY.vi : MATERIAL_COPY.en;
}
