export const followupCopy = {
  en: {
    title: "Learner follow-up",
    back: "Back to class attention",
    loading: "Loading learner evidence…",
    unavailable:
      "Learner evidence could not be loaded. This does not mean there is no work.",
    forbidden:
      "This learner's evidence is not available with your current access.",
    retry: "Try again",
    current: "Current signals",
    resolved:
      "No current attention signals in this period. The records may have changed since you opened the list.",
    changed: "The selected signal is no longer present in the current records.",
    work: "Assignments and work",
    empty: "No assignments are available for this learner.",
    due: "Due",
    submitted: "Submitted",
    noDate: "Not recorded",
    noDue: "No due date",
    review: "Review work",
    inspect: "Open assignment",
    context: "Assignment opens in the existing class assignment workspace.",
    attendance: "Recorded attendance",
    noAttendance: "No attendance records in this period.",
    weaknesses: "Study-plan evidence",
    noWeakness: "No demonstrated study-plan weaknesses in this period.",
    weakUnavailable:
      "Study-plan evidence is unavailable. No conclusion can be drawn from missing data.",
    learnerWide:
      "These are learner-wide study-plan records; they are not attributed to a class assignment.",
    evidence: "evidence records",
    lastEvidence: "Last evidence",
    related: "Linked to the attention signal",
    other: "Other available work",
    late: "Submitted after the due date",
    score: "Score",
    band: "Overall band",
    provisional: "Provisional band",
    reasons: {
      overdue_assignment:
        "Assignments past their due date without a submission",
      critical_weakness: "Demonstrated skills needing practice",
      repeated_absence: "Recorded absences in this period",
    },
    statuses: {
      inactive: "Assignment not active",
      resubmit: "Resubmission requested",
      returned: "Returned",
      overdue: "Overdue · not submitted",
      inProgress: "In progress · not submitted",
      notStarted: "Not submitted",
      pending: "Submitted · awaiting review",
      graded: "Graded",
      completed: "Submitted · no pending teacher review",
    },
    attendanceStatuses: {
      present: "Present",
      late: "Late",
      absent: "Absent",
      excused: "Excused",
    },
  },
  vi: {
    title: "Theo dõi học viên",
    back: "Quay lại danh sách cần chú ý",
    loading: "Đang tải bằng chứng học tập…",
    unavailable:
      "Không thể tải bằng chứng học tập. Điều này không có nghĩa là học viên chưa làm bài.",
    forbidden:
      "Quyền truy cập hiện tại không cho phép xem bằng chứng của học viên này.",
    retry: "Thử lại",
    current: "Tín hiệu hiện tại",
    resolved:
      "Không có tín hiệu cần chú ý trong giai đoạn này. Dữ liệu có thể đã thay đổi từ lúc mở danh sách.",
    changed: "Tín hiệu đã chọn không còn xuất hiện trong dữ liệu hiện tại.",
    work: "Bài tập và bài làm",
    empty: "Chưa có bài tập khả dụng cho học viên này.",
    due: "Hạn nộp",
    submitted: "Đã nộp",
    noDate: "Chưa ghi nhận",
    noDue: "Không có hạn nộp",
    review: "Xem và chấm bài",
    inspect: "Mở bài tập",
    context: "Bài tập mở trong không gian bài tập hiện có của lớp.",
    attendance: "Điểm danh đã ghi nhận",
    noAttendance: "Chưa có dữ liệu điểm danh trong giai đoạn này.",
    weaknesses: "Bằng chứng từ kế hoạch học",
    noWeakness: "Chưa ghi nhận điểm yếu từ kế hoạch học trong giai đoạn này.",
    weakUnavailable:
      "Bằng chứng từ kế hoạch học chưa khả dụng. Không thể kết luận từ dữ liệu còn thiếu.",
    learnerWide:
      "Đây là dữ liệu kế hoạch học cá nhân, không gắn với một bài tập cụ thể của lớp.",
    evidence: "bằng chứng",
    lastEvidence: "Bằng chứng gần nhất",
    related: "Liên quan đến tín hiệu cần chú ý",
    other: "Bài làm khác hiện có",
    late: "Nộp sau hạn",
    score: "Điểm",
    band: "Band tổng",
    provisional: "Band tạm tính",
    reasons: {
      overdue_assignment: "Bài tập đã quá hạn nhưng chưa nộp",
      critical_weakness: "Kỹ năng cần luyện tập theo bằng chứng",
      repeated_absence: "Buổi vắng đã ghi nhận trong giai đoạn này",
    },
    statuses: {
      inactive: "Bài tập không hoạt động",
      resubmit: "Yêu cầu nộp lại",
      returned: "Đã trả bài",
      overdue: "Quá hạn · chưa nộp",
      inProgress: "Đang làm · chưa nộp",
      notStarted: "Chưa nộp",
      pending: "Đã nộp · chờ chấm",
      graded: "Đã chấm",
      completed: "Đã nộp · không còn yêu cầu chấm",
    },
    attendanceStatuses: {
      present: "Có mặt",
      late: "Đi muộn",
      absent: "Vắng",
      excused: "Vắng có phép",
    },
  },
};
