steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=services/ai-grading-worker/Dockerfile
      - --tag=${_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    args: [push, ${_IMAGE}]
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: asia-southeast1-docker.pkg.dev/thinkfy-debatelab-prod/debatelab-workers/ai-grading-worker:manual
options:
  logging: CLOUD_LOGGING_ONLY
