type CenterCopy = {
  [key: string]: string;
};

export const centerCopy: Record<"en" | "vi", CenterCopy> = {
  en: {
    title: "Center operations",
    active: "Active",
    enrolled: "Enrolled",
    booked: "Booked",
    draft: "Draft",
    failed: "Failed",
    exception: "Needs review",
    sandbox: "Test mode",
    not_connected: "Not connected",
    not_submitted: "Not submitted",
    completed: "Completed",
    skipped: "Skipped",
    processing: "Processing",
    disabled: "Disabled",
    reconnect_required: "Reconnect required",

    students: "Students",
    trials: "Trials",
    schedules: "Schedules",
    tuition: "Tuition",
    materials: "Materials",
    integrations: "Integrations",
    assistant: "Assistant",
    refresh: "Refresh",
    addStudent: "Add student",
    save: "Save",
    addNote: "Add note",
    notes: "Notes",
    details: "Details",
    source: "Source",
    target: "Target",
    stage: "Stage",
    class: "Class",
    name: "Name",
    phone: "Phone",
    email: "Email",
    lead: "Lead",
    qualified: "Qualified",
    lost: "Lost",
    bookTrial: "Book trial",
    start: "Start · Vietnam time",
    end: "End · Vietnam time",
    mark: "Mark",
    attended: "Attended",
    noShow: "No-show",
    no_show: "No-show",
    cancelled: "Cancelled",
    evaluate: "Evaluate",
    level: "Level",
    strengths: "Strengths",
    weaknesses: "Areas to improve",
    recommendation: "Recommendation",
    offer: "Create offer",
    amount: "Amount (VND)",
    offerStart: "Start date",
    offerEnd: "End date",
    invoice: "Invoice",
    checkout: "Generate checkout",
    cancel: "Cancel",
    renewal: "Renewal",
    pending: "Pending — checkout readiness",
    connect: "Connect Google",
    prepare: "Prepare",
    disconnected: "Disconnected",
    ready: "Ready",
    scopes: "Scopes",
    account: "Account",
    lastSync: "Last sync",
    bindings: "Bindings",
    jobs: "Jobs",
    ask: "Ask about this center…",
    send: "Send",
    sources: "Sources",
    proposal: "Review proposal",
    confirm: "Confirm",
    cancelProposal: "Cancel proposal",
    empty: "Nothing here yet.",
    error: "Something went wrong. Your input is still here.",
    required: "Required",
    selectStudent: "Select student",
    selectClass: "Select class",
    guardianInvite: "Invite guardian",
    guardianName: "Guardian full name",
    createInvite: "Create claim link",
    inviteReady: "Shareable claim link",
    alreadyCreated: "An invite already exists",
    openCheckout: "Open checkout",
    reschedule: "Reschedule",
    emptySchedules: "No schedules yet.",
    guardianConsent:
      "The recipient must verify their identity before claiming access",
    offered: "Offered",
    open: "Open",
    paid: "Paid",
    connected: "Connected",
    pendingStatus: "Pending",
    executed: "Completed",
    cancelledStatus: "Cancelled",
  },
  vi: {
    title: "Vận hành trung tâm",
    active: "Đang học",
    enrolled: "Đã ghi danh",
    booked: "Đã đặt",
    draft: "Bản nháp",
    failed: "Không thành công",
    exception: "Cần kiểm tra",
    sandbox: "Thử nghiệm",
    not_connected: "Chưa kết nối",
    not_submitted: "Chưa gửi",
    completed: "Hoàn tất",
    skipped: "Đã bỏ qua",
    processing: "Đang xử lý",
    disabled: "Đã tắt",
    reconnect_required: "Cần kết nối lại",

    students: "Học viên",
    trials: "Học thử",
    schedules: "Lịch học",
    tuition: "Học phí",
    materials: "Tài liệu",
    integrations: "Tích hợp",
    assistant: "Trợ lý",
    refresh: "Làm mới",
    addStudent: "Thêm học viên",
    save: "Lưu",
    addNote: "Thêm ghi chú",
    notes: "Ghi chú",
    details: "Chi tiết",
    source: "Nguồn",
    target: "Mục tiêu",
    stage: "Giai đoạn",
    class: "Lớp",
    name: "Họ tên",
    phone: "Điện thoại",
    email: "Email",
    lead: "Tiềm năng",
    qualified: "Đủ điều kiện",
    lost: "Mất liên hệ",
    bookTrial: "Đặt học thử",
    start: "Bắt đầu · giờ Việt Nam",
    end: "Kết thúc · giờ Việt Nam",
    mark: "Cập nhật",
    attended: "Đã học",
    noShow: "Vắng",
    no_show: "Vắng",
    cancelled: "Đã hủy",
    evaluate: "Đánh giá",
    level: "Trình độ",
    strengths: "Điểm mạnh",
    weaknesses: "Điểm cần cải thiện",
    recommendation: "Đề xuất",
    offer: "Tạo đề nghị",
    amount: "Số tiền (VND)",
    offerStart: "Ngày bắt đầu",
    offerEnd: "Ngày kết thúc",
    invoice: "Hóa đơn",
    checkout: "Tạo liên kết thanh toán",
    cancel: "Hủy",
    renewal: "Gia hạn",
    pending: "Chờ xử lý — sẵn sàng thanh toán",
    connect: "Kết nối Google",
    prepare: "Chuẩn bị",
    disconnected: "Chưa kết nối",
    ready: "Sẵn sàng",
    scopes: "Quyền",
    account: "Tài khoản",
    lastSync: "Đồng bộ gần nhất",
    bindings: "Liên kết",
    jobs: "Tác vụ",
    ask: "Hỏi về trung tâm…",
    send: "Gửi",
    sources: "Nguồn tham khảo",
    proposal: "Xem lại đề xuất",
    confirm: "Xác nhận",
    cancelProposal: "Hủy đề xuất",
    empty: "Chưa có dữ liệu.",
    error: "Đã xảy ra lỗi. Nội dung bạn nhập vẫn được giữ lại.",
    required: "Bắt buộc",
    selectStudent: "Chọn học viên",
    selectClass: "Chọn lớp",
    guardianInvite: "Mời người giám hộ",
    guardianName: "Họ tên người giám hộ",
    createInvite: "Tạo liên kết nhận",
    inviteReady: "Liên kết nhận",
    alreadyCreated: "Lời mời đã tồn tại",
    openCheckout: "Mở thanh toán",
    reschedule: "Đổi lịch",
    emptySchedules: "Chưa có lịch học.",
    guardianConsent:
      "Người nhận phải xác minh danh tính trước khi nhận quyền truy cập",
    offered: "Đã đề nghị",
    open: "Đang mở",
    paid: "Đã thanh toán",
    connected: "Đã kết nối",
    pendingStatus: "Đang chờ",
    executed: "Đã hoàn tất",
    cancelledStatus: "Đã hủy",
  },
} as const;
